INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Napoleon Hill','Whatever the mind of man can conceive and believe, it can achieve.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Albert Einstein','Strive not to be a success, but rather to be of value.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Robert Frost','Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Florence Nightingale','I attribute my success to this: I never gave or took any excuse.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Wayne Gretzky','You miss 100% of the shots you don’t take.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Amelia Earhart','The most difficult thing is the decision to act, the rest is merely tenacity.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Babe Ruth','Every strike brings me closer to the next home run.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('W. Clement Stone','Definiteness of purpose is the starting point of all achievement.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('John Lennon','Life is what happens to you while you’re busy making other plans.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Earl Nightingale','We become what we think about.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Charles Swindoll','Life is 10% what happens to me and 90% of how I react to it.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Alice Walker','The most common way people give up their power is by thinking they don’t have any.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Buddha','The mind is everything. What you think you become.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Chinese Proverb','The best time to plant a tree was 20 years ago. The second best time is now.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Socrates','An unexamined life is not worth living.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Woody Allen','Eighty percent of success is showing up.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Steve Jobs','Your time is limited, so don’t waste it living someone else’s life.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Vince Lombardi','Winning isn’t everything, but wanting to win is.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Stephen Covey','I am not a product of my circumstances. I am a product of my decisions.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Pablo Picasso','Every child is an artist.  The problem is how to remain an artist once he grows up.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Christopher Columbus','You can never cross the ocean until you have the courage to lose sight of the shore.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Jim Rohn','Either you run the day, or the day runs you.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Henry Ford','Whether you think you can or you think you can’t, you’re right.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Mark Twain','The two most important days in your life are the day you are born and the day you find out why.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Johann Wolfgang von Goethe','Whatever you can do, or dream you can, begin it.  Boldness has genius, power and magic in it.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Frank Sinatra','The best revenge is massive success.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Aristotle','There is only one way to avoid criticism: do nothing, say nothing, and be nothing.');
INSERT INTO QUOTE (AUTHOR,NAME) VALUES ('Me','Test Quote');
